version: '3'

networks: 
  stack:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.29.0.0/16

services:
  api:
    image: test/qrpague:latest
    networks:
        - stack
    depends_on:
        - mongo
    ports:
        - "9999:8080"
    volumes:
        - ~/dev/workspace/qrpague-server/templates:/home/qrpague/templates
    environment:
        AMBIENTE: 'development'
        PORT: 8080
        NODE_PROJECT: 'QR-Pague Service'
        LOG_LEVEL: 'error'
        MONGO_CONNECTION : 'mongodb://mongo:27017/QRPAGUE'
        MONGOOSE_DEBUG: 'true'
        SERVER_URL : 'http://127.0.0.1:8080'
        QRPAGUE_URL: 'http://127.0.0.1:8080/operacoes'
        ERROR_MESSAGE_FILE: '/home/qrpague/templates/message/error-messages.yaml'
        WHATSAPP_TEMPLATE_FILE: '/home/qrpague/templates/whatsapp/shareLink.html'
        INSTITUICOES_FILE: '/home/qrpague/templates/instituicoes/instituicoes.yaml'
        WHATSAPP_IMAGE_URL: 'https://avatars1.githubusercontent.com/u/43270555?s=460&v=4'
  mongo:
    image: mongo:4.1
    networks:
        - stack
