version: '3'

networks: 
  stack:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.29.0.0/16

services:
  api:
    image: qrpague/qrpague-api:latest
    networks:
        - stack
    depends_on:
        - mongo
    ports:
        - "9999:8080"
    environment:
        MONGO_CONNECTION : 'mongodb://mongo:27017/QRPAGUE'
        SERVER_URL : 'http://127.0.0.1:8080'
  mongo:
    image: mongo:4.1
    networks:
        - stack
