swagger: "2.0"

info:
  description: >-
    A solução QRPague utiliza as tecnologias de QRCode e API para implementar
    operações financeiras de saque, pagamentos e transferência entre
    instituições distintas, sendo elas financeiras ou não. Esta API fornece um
    conjunto de serviços de emissão, autorização e confirmação de operações
    financeiras online. O uso das APIs deve obedecer os fluxos de processo
    disponíveis no GitHub do projeto para cada natureza de operação (saque,
    transferência ou pagamento).
  version: v1
  title: Operações Digitais QRPague
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: dev@sicoob.com.br

host: qrpague.sicoob.com.br
basePath: /qrpague
schemes:
  - https

paths:
  /operacoes:
    post:
      tags:
        - Operações Financeiras Digitais
      summary: Endpoit para gerar um QRCode de operação financeira digital.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para que
        um cliente/beneficiário possa solicitar a geração de um QRCode para uma
        operação financeira digital.
      operationId: criarOperacao
      security:
        - OAuth2: [qrpague_operacao_cadastro]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    get:
      tags:
        - Operações Financeiras Digitais
      summary: >-
        Endpoit para recuperar informações de operações financeiras digitais
        através da url QRPAGUE codifica no QRCode gerado pela instituição
        cedente.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver as informações complementares de uma operação financeira
        digital gerada através da solução QRPague pelo parâmetro uuid.
      operationId: consultarOperacoes
      security:
        - OAuth2: [qrpague_operacao_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes/{uuid}':
    get:
      tags:
        - Operações Financeiras Digitais
      summary: >-
        Endpoit para consultar informações de uma operação financeira digital
        (Transferência, Saque ou Pagamento) gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        recuperar as informações de uma operação financeira digital
        (Transferência, Saque ou Pagamento) identificada pelo UUID passado como
        parâmetro. 
      operationId: consultarOperacao
      security:
        - OAuth2: [qrpague_operacao_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes/{uuid}/efetivacao':
    put:
      tags:
        - Operações Financeiras Digitais
      summary: >-
        Endpoit para receber a efetivação de execução com sucesso de uma
        operação financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        receber a confirmação da efetivação de uma operação financeira digital
        gerada através da solução QRPague e identificada pelo seu uuid.
      operationId: efetivarOperacao
      security:
        - OAuth2: [qrpague_operacao_efetivacao]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes/{uuid}/confirmacao':
    put:
      tags:
        - Operações Financeiras Digitais
      summary: >-
        Endpoint para confirmar a entrega de um produto de uma
        operação financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        receber a confirmação do recebimento de uma operação financeira digital
        gerada através da solução QRPague e identificada pelo seu uuid.
      operationId: confirmarOperacao
      security:
        - OAuth2: [qrpague_operacao_confirmacao]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/operacoes/{uuid}/pagamentos':
    post:
      tags:
        - Pagamentos
      summary: >-
        Endpoit para registrar pagamento de uma operação financeira digital
        gerada através do QRPague.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        registrar um pagamento para realização de uma operação financeira
        digital gerada através da solução QRPague e identificada pelo seu uuid.
      operationId: operacao-financeira-pagar
      security:
        - OAuth2: [qrpague_pagamento_cadastro]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /pagamentos:
    get:
      tags:
        - Pagamentos
      summary: >-
        Endpoit para recuperar informações de pagamentos vinculados a operações
        financeiras digitais através da url QRPAGUE codifica no QRCode gerado
        pela instituição cedente.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver as informações de pagaemntos ligados a operações financeira
        digitais gerada através da solução QRPague pelo parâmetro uuid.
      operationId: pagamentos-recuperar
      security:
        - OAuth2: [qrpague_pagamento_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/pagamentos/{uuid}':
    get:
      tags:
        - Pagamentos
      summary: >-
        Endpoit para consultar informações de um pagamento ligado a uma operação
        financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        recuperar as informações de um pagamento ligado a uma operação
        financeira digital identificada pelo UUID passado como parâmetro. 
      operationId: pagamento-consultar
      security:
        - OAuth2: [qrpague_pagamento_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/pagamentos/{uuid}/confirmacao':
    put:
      tags:
        - Pagamentos
      summary: >-
        Endpoit para receber a confirmação de pagamentos de uma operação
        financeira digital gerada através do QRPAGUE.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        receber a confirmação da efetivação de pagamentos ligados a uma operação
        financeira digital gerada através da solução QRPague e identificada pelo
        seu uuid.
      operationId: pagamento-confirmar
      security:
        - OAuth2: [qrpague_pagamento_confirmacao]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  
  /beneficiarios:
    get:
      tags:
        - Beneficiário
      summary: >-
        Endpoit para recuperar informações de beneficiários vinculados a operações
        financeiras digitais através do CPF ou CNPJ.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver as informações de beneficiários ligados a operações financeiras
        digitais geradas através da solução QRPague.
      operationId: consultarBeneficiarios
      security:
        - OAuth2: [qrpague_beneficiario_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  '/beneficiarios/{cpfCnpj}':
    get:
      tags:
        - Beneficiário
      summary: >-
        Endpoit para recuperar informações de um beneficiário vinculado a operações
        financeiras digitais através do CPF ou CNPJ.
      description: >-
        Este endpoint deve ser implementado pela instituição financeira para
        devolver as informações de um beneficiário ligado a operações financeiras
        digitais geradas através da solução QRPague.
      operationId: consultarBeneficiario
      security:
        - OAuth2: [qrpague_beneficiario_consulta]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      
securityDefinitions:
  OAuth2:
    type: oauth2
    authorizationUrl: 'https://<<uri>>/oauth/authorize'
    tokenUrl: 'https://<<uri>>/token'
    flow: accessCode
    scopes:
      qrpague_operacao_cadastro: Autoriza recurso para gerar uma operação financeira digital.
      qrpague_operacao_consulta: Autoriza recurso para consultar operação financeira digital.
      qrpague_operacao_efetivacao: Autoriza recurso para efetivar uma operação financeira digital.
      qrpague_operacao_confirmacao: Autoriza recurso para confirmar uma operação financeira digital.
      qrpague_pagamento_cadastro: Autoriza recurso para gerar pagamento.
      qrpague_pagamento_consulta: Autoriza recurso para consultar pagamento.
      qrpague_pagamento_confirmacao: Autoriza recurso para confirmar pagamento.
      qrpague_beneficiario_consulta: Autoriza recurso para consultar beneficiario.
